name: Notion Sync

on:
  push:
    branches: [ main ]
    paths:
      - '**/docs/**/*.md'  # Only trigger on markdown files in docs folders
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install @notionhq/client
        
      - name: Sync to Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_READING_LIST_ID: ${{ secrets.NOTION_READING_LIST_ID }}
          NOTION_WORKSPACE_ID: ${{ secrets.NOTION_WORKSPACE_ID }}
        run: node .github/scripts/sync-to-notion.js
        
      - name: Sync from Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_WORKSPACE_ID: ${{ secrets.NOTION_WORKSPACE_ID }}
        run: node .github/scripts/sync-from-notion.js
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Sync with Notion" && git push) 